import './globals.css'
import {Inter} from 'next/font/google'
import React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-in",
});

export const metadata = {
    title: 'What, Why, How',
    description: 'Generated by create next app',
}

const cx = (...classNames: string[]) => classNames.filter(Boolean).join(" ");


export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={cx(inter.variable, "font-mr bg-light dark:bg-dark")}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    )
}
