import './globals.css'
import {Inter} from 'next/font/google'
import Script from "next/script";
import React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-in",
});

export const metadata = {
    title: 'What, Why, How',
    description: 'Generated by create next app',
}

const cx = (...classNames: string[]) => classNames.filter(Boolean).join(" ");


export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={cx(inter.variable, "font-mr bg-light dark:bg-dark")}>
        <Script id="theme-switcher" strategy="beforeInteractive">
            {`if (localStorage.getItem('theme') === 'dark' || 
                (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                document.documentElement.classList.add('dark')
            } else {
                document.documentElement.classList.remove('dark')
            }`}
        </Script>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    )
}
